version: '3.4'

volumes:
  datafiles:

services:
  db:
    image: mysql
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    
  mvcmovie:
    image: mvcmovie
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    restart: always
    environment:
      - DBHOST=db
      - DBUSER=root
      - DBPASS=password
      - ASPNETCORE_ENVIRONMENT=Development
